### ISSUE TITLE
About the eglibc srcdir is appended with /libc 

### ISSUE THREAD

**Issue by s86097john** [archi/abe#1]
@ryanarn 

1. I have a problem when I build the eglibc library. The error message shows that abe can not find the eglibc configure file. by the way, I use the stable branch in the linaro abe git.

2. And , I saw that the patch: [https://git.linaro.org/toolchain/abe.git/commit/98434210019c4fc526c5573a07d65481b0a23484](url)

3. It seems like it would cause abe to manage the folder in the following way:
    (a) **/path/to/may/snapshot/eglibc.git~linaro_eglibc-2_19/libc/
    .git/
    libc/ => where the configure file is actually located
    linuxthreads/
    localedef/
    ports/**
    but what we want is:
    (b)**/path/to/may/snapshot/eglibc.git~linaro_eglibc-2_19/
    .git/
    libc/ => where the configure file is actually located
    linuxthreads/
    localedef/
    ports/**

4.  I understand the reason why the srcdir need to be appended with the /libc . => we will need this to find the configure file later. 
     In the situation (b), this patch will just work fine. So, where should I modified to get  situation (b) , and do not have to delete the /libc in the component.sh ?

**Comment by archi** [comment]
Hey John, this repo is
a) not affiliated with the Linaro Toolchain Workgroup
b) and most important: out of date.

You should use https://git.linaro.org/toolchain/abe.git and report any bugs/issues/errors to the Linaro TCWG.

I should probably delete this repo,...

**Comment by s86097john** [comment]
Thanks for the reply
I will try to contact the Linaro by their bugzilla system.
Yo can remove this issue thread.
Sorry for mistaking this repo......

**Comment by archi** [comment]
No problem ;) good luck with the issue.
